from cards import *
from config import *
global activePlayer
global playerCount
activatePlayer = 1
playerCount = 6
discardPile = []
playerHand = {
    1 : [],
    2 : [],
    3 : [],
    4 : [],
    5 : [],
    6 : []
}
playerParties = {
    1 : {
        #Front Row
        "Hero" : {
            1: Leaders["None"],
            "1 Active" : False,
            2: Leaders["None"],
            "2 Active" : False,
            3: Leaders["None"],
            "3 Active" : False,
            4: Leaders["None"],
            "4 Active" : False,
            5: Leaders["None"],
            "5 Active" : False,
            6: Leaders["None"],
            "6 Active" : False,
            7: Leaders["None"],
            "7 Active" : False,
            },
        #Back Row
        "Leader"  : Leaders["None"],
        "Monster" : {
            1: Monsters["None"],
            "1 Active" : False,
            2: Monsters["None"],
            "2 Active" : False,
            3: Monsters["None"],
            "3 Active" : False,
            4: Monsters["None"],
            "4 Active" : False,
            },
        "Banner"  : {
            1: Banners["None"],
            "1 Active" : False,
            2: Banners["None"],
            "2 Active" : False,
            3: Banners["None"],
            "3 Active" : False,
            4: Banners["None"],
            "4 Active" : False,
            },
    },
    2 : {
        #Front Row
        "Hero" : {
            1: Leaders["None"],
            "1 Active" : False,
            2: Leaders["None"],
            "2 Active" : False,
            3: Leaders["None"],
            "3 Active" : False,
            4: Leaders["None"],
            "4 Active" : False,
            5: Leaders["None"],
            "5 Active" : False,
            6: Leaders["None"],
            "6 Active" : False,
            7: Leaders["None"],
            "7 Active" : False,
            },
        #Back Row
        "Leader"  : Leaders["None"],
        "Monster" : {
            1: Monsters["None"],
            "1 Active" : False,
            2: Monsters["None"],
            "2 Active" : False,
            3: Monsters["None"],
            "3 Active" : False,
            4: Monsters["None"],
            "4 Active" : False,
            },
        "Banner"  : {
            1: Banners["None"],
            "1 Active" : False,
            2: Banners["None"],
            "2 Active" : False,
            3: Banners["None"],
            "3 Active" : False,
            4: Banners["None"],
            "4 Active" : False,
            },
    },
    3 : {
        #Front Row
        "Hero" : {
            1: Leaders["None"],
            "1 Active" : False,
            2: Leaders["None"],
            "2 Active" : False,
            3: Leaders["None"],
            "3 Active" : False,
            4: Leaders["None"],
            "4 Active" : False,
            5: Leaders["None"],
            "5 Active" : False,
            6: Leaders["None"],
            "6 Active" : False,
            7: Leaders["None"],
            "7 Active" : False,
            },
        #Back Row
        "Leader"  : Leaders["None"],
        "Monster" : {
            1: Monsters["None"],
            "1 Active" : False,
            2: Monsters["None"],
            "2 Active" : False,
            3: Monsters["None"],
            "3 Active" : False,
            4: Monsters["None"],
            "4 Active" : False,
            },
        "Banner"  : {
            1: Banners["None"],
            "1 Active" : False,
            2: Banners["None"],
            "2 Active" : False,
            3: Banners["None"],
            "3 Active" : False,
            4: Banners["None"],
            "4 Active" : False,
            },
    },
    4 : {
        #Front Row
        "Hero" : {
            1: Leaders["None"],
            "1 Active" : False,
            2: Leaders["None"],
            "2 Active" : False,
            3: Leaders["None"],
            "3 Active" : False,
            4: Leaders["None"],
            "4 Active" : False,
            5: Leaders["None"],
            "5 Active" : False,
            6: Leaders["None"],
            "6 Active" : False,
            7: Leaders["None"],
            "7 Active" : False,
            },
        #Back Row
        "Leader"  : Leaders["None"],
        "Monster" : {
            1: Monsters["None"],
            "1 Active" : False,
            2: Monsters["None"],
            "2 Active" : False,
            3: Monsters["None"],
            "3 Active" : False,
            4: Monsters["None"],
            "4 Active" : False,
            },
        "Banner"  : {
            1: Banners["None"],
            "1 Active" : False,
            2: Banners["None"],
            "2 Active" : False,
            3: Banners["None"],
            "3 Active" : False,
            4: Banners["None"],
            "4 Active" : False,
            },
    },
    5 : {
        #Front Row
        "Hero" : {
            1: Leaders["None"],
            "1 Active" : False,
            2: Leaders["None"],
            "2 Active" : False,
            3: Leaders["None"],
            "3 Active" : False,
            4: Leaders["None"],
            "4 Active" : False,
            5: Leaders["None"],
            "5 Active" : False,
            6: Leaders["None"],
            "6 Active" : False,
            7: Leaders["None"],
            "7 Active" : False,
            },
        #Back Row
        "Leader"  : Leaders["None"],
        "Monster" : {
            1: Monsters["None"],
            "1 Active" : False,
            2: Monsters["None"],
            "2 Active" : False,
            3: Monsters["None"],
            "3 Active" : False,
            4: Monsters["None"],
            "4 Active" : False,
            },
        "Banner"  : {
            1: Banners["None"],
            "1 Active" : False,
            2: Banners["None"],
            "2 Active" : False,
            3: Banners["None"],
            "3 Active" : False,
            4: Banners["None"],
            "4 Active" : False,
            },
    },
    6 : {
        #Front Row
        "Hero" : {
            1: Leaders["None"],
            "1 Active" : False,
            2: Leaders["None"],
            "2 Active" : False,
            3: Leaders["None"],
            "3 Active" : False,
            4: Leaders["None"],
            "4 Active" : False,
            5: Leaders["None"],
            "5 Active" : False,
            6: Leaders["None"],
            "6 Active" : False,
            7: Leaders["None"],
            "7 Active" : False,
            },
        #Back Row
        "Leader"  : Leaders["None"],
        "Monster" : {
            1: Monsters["None"],
            "1 Active" : False,
            2: Monsters["None"],
            "2 Active" : False,
            3: Monsters["None"],
            "3 Active" : False,
            4: Monsters["None"],
            "4 Active" : False,
            },
        "Banner"  : {
            1: Banners["None"],
            "1 Active" : False,
            2: Banners["None"],
            "2 Active" : False,
            3: Banners["None"],
            "3 Active" : False,
            4: Banners["None"],
            "4 Active" : False,
            },
    },
}