rankedList = [
"Bad Axe",
"Bear Claw",
"Beary Wise",
"Fury Knuckle",
"Heavy Bear",
"Pan Chucks",
"Qi Bear",
"Tough Teddy"
#"Dodgy Dealer",
"Fuzzy Cheeks",
"Greedy Cheeks",
"Lucky Bucky",
"Mellow Dee",
"Napping Nibbles",
"Peanut",
"Tipsy Tootie",
"Calming Voice",
"Guiding Light",
"Holy Curselifter",
"Iron Resolve",
"Mighty Blade",
"Radiant Horn",
#"Vibrant Glow",
"Wise Shield",
"Bullseye",
"Hook",
"Lookie Rookie",
"Quick Draw",
"Serious Grey",
"Sharp Fox",
"Wildshot",
"Wily Red",
"Kit Napper",
"Meowzio",
"Plundering Puma",
"Shurikitty",
"Silent Shadow",
"Slippery Paws",
"Sly Pickings",
"Smooth Mimimeow",
"Bun Bun",
"Buttons",
"Fluffy",
"Hopper",
"Snowball",
"Spooky",
"Whiskers",
"Wiggles",
"Big Buckley",
"Buck Omens",
"Doe Fallow",
"Glowing Antler",
"Maegisty",
"Magus Moose",
"Majestelk",
"Stagguard",
"Agile Dagger",
"Blinding Blade",
"Critical Fang",
"Hardened Hunter",
"Looting Lupo",
"Silent Shield",
"Tenacious Timber",
"Wolfgang Pack",
"Bark Hexer",
"Beholden Retriever",
"Bone Collector",
"Boston Terror"
#"Grim Pupper",
"Hollow Husk",
"Perfect Vessel",
"Shadow Saint",
"Annihilator",
"Brawling Spirit",
"Gruesome Gladiator",
"Meowntain",
"Rabid Beast",
"Roaryal Guard",
"Vicious Wildcat",
"Unbridled Fury",
"Dragalter"
#"Dystortivern",
"Extraga",
"Luut",
"Mirroryu",
"Oracon",
"Renovern",
"Shamanaga",
"Smok",
"Hamlet",
"Bearserker",
"Complex Illusion",
"Enchantler",
"Hoodwink",
"Purring Bandit",
"Nimble Gray",
"Mimi",
"Gift Bearer",
"Santa Claws",
"Christmas Carol",
"Lil' Drummer Bard",
"Shiny Nose",
"Snow Slinger",
"Prancer",
"Shooting Star",
"Fireplace Fugitive",
"Gift Bag Bandit",
"Evergreen",
"Holly Jolly"
]
rankedMonsterBanlist = [
    "Venomous Gemini"
]